### PR TITLE
Bump deployment target consistent with SDWebImage

### PR DESCRIPTION
**Pull request by zhongwuzw**

### CODE REVIEW

**Comment by dreampiggy** [comment]
APNG format support was introduced after these firmware version. Changing these will cause the runtime crash for the lower version firmware.

+ iOS 8.0+
+ macOS 10.10+
+ tvOS 9.0+
+ watchOS 2.0+

See [kCGImagePropertyAPNGDelayTime](https://developer.apple.com/documentation/imageio/kcgimagepropertyapngdelaytime)

**Comment by zhongwuzw** [comment]
@dreampiggy Oops, I forgot this restrict, it would crash on older firmware? I think it only just invalid. What about [SDWebImageHEIFCoder](https://github.com/SDWebImage/SDWebImageHEIFCoder/blob/master/SDWebImageHEIFCoder.podspec)? `SDWebImageHEIFCoder` deploy to `iOS8` in the `podspec`.

**Comment by dreampiggy** [comment]
SDWebImageHEIFCoder does not plan to keep iOS 7 && macOS 9 compatible, because the static library (libx265 libde265 libheif) was built with Xcode 9. I don't test whether it's safe or ABI compatible for lower fireware... And the API using in the master branch use the 5.x `SDImageCoder` API but not 4.x one.

If you really want to use it on iOS 7, maybe you can fork and create a compatible branch (change the API to use 4.x's `SDWebImageCoder` protocol). And also you need to check whether the static library is compatible for iOS 7.

**Comment by zhongwuzw** [comment]
@dreampiggy Emm, `.a` static file only related to platform architecture, like `i386`、`arm64`, no relationship with `target` or `system version`、`Xcode version`.

Let's assume that have an app, its minimum target is `iOS7`, it wants to use `SDWebImageAPNGCoder` for user who device system is greater than `iOS7` but using other format on `iOS7` , how user can import it using `CocoaPods`?

**Comment by dreampiggy** [comment]
@zhongwuzw The static library was built with iOS 8 min-deployment target version && macOS 10.10 min-deployment target version. Using iOS 12 SDK && macOS 10.13 SDK.

So what you think about this warning by ld was used for ? [ld: warning: object file (Frameworks/xx.framework/xx(xx.o)) was built for newer iOS version (9.0) than being linked (8.0)](https://stackoverflow.com/questions/32270491/xcode-7-warning-was-built-for-newer-ios-version-5-1-1-than-being-linked-5-1)

**Comment by zhongwuzw** [comment]
@dreampiggy You can check the structure of `framework`, `.a` has no any system info.

image

**Pull request closed without merging**
